# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: cargo-check
  - id: fmt

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: local
  hooks:
  - id: ktlint-check
    name: ktlint check
    entry: ktlint
    language: system
    types: [kotlin]
    args: [--relative]

  - id: ktlint-format
    name: ktlint format
    entry: ktlint
    language: system
    types: [kotlin]
    args: [-F, --relative]

- repo: https://github.com/Cretezy/dart-format-pre-commit
  rev: master
  hooks:
  - id: dart-format
